### ISSUE TITLE
RC1 does not like Compact Solars

### ISSUE THREAD

**Issue by Gamoholic** [asiekierka/asielauncher#16]
The first time it complained, it said something about the Compact Solars mod. I am running this in a screen, so I can't scroll up.

Here is the normal output:

[INFO] Checking for updates...
[INFO] Started ALSO 0.4.0-rc1
[INFO] [Launcher] Generating launcher JAR...
[INFO] Preparing directories
[INFO] Added directory mods
[INFO] Added directory coremods
[INFO] Added directory bin
[INFO] Added directory lib
[INFO] Added ZIP directory config
[INFO] Added ZIP directory root
[INFO] [FileParser] Scanning through mod files...

SyntaxError: Unexpected token }
    at Object.parse (native)
    at /minecraft/1.5_experimental_pack/AsieLauncher/internal/fileParser.js:52:21
    at /minecraft/1.5_experimental_pack/AsieLauncher/internal/fileParser.js:27:4
    at Array.forEach (native)
    at Function._.each._.forEach (/minecraft/1.5_experimental_pack/node_modules/underscore/underscore.js:79:11)
    at /minecraft/1.5_experimental_pack/AsieLauncher/internal/fileParser.js:26:5
    at Array.forEach (native)
    at Function._.each._.forEach (/minecraft/1.5_experimental_pack/node_modules/underscore/underscore.js:79:11)
    at runList (/minecraft/1.5_experimental_pack/AsieLauncher/internal/fileParser.js:25:4)
    at Object.exports.getModList (/minecraft/1.5_experimental_pack/AsieLauncher/internal/fileParser.js:35:2)

Here is the --debug output: http://pastebin.com/EvA2Eq9V

**Comment by asiekierka** [comment]
Could you please send the ZIP file for CompactSolars? And whatever comes after Biomes'o'Plenty in your pack. (I tried CompactSolars 4.2.0.53 or so and it worked effortlessly)

I will also work on better error handling.

**Comment by asiekierka** [comment]
Added better error handling in the newest update (still called rc2). Could you look into it now?

**Comment by Gamoholic** [comment]
RC2 does fix the problem. Also, it was Compact Windmills, not Compact Solars. I was close :P 

New question: why does it dump my server.properties, even on the normal "node also"?

Just in case it is helpful, here is the full --debug output: http://pastebin.com/u1kkKSr5

**Comment by asiekierka** [comment]
Just some debug code i forgot to remove.

I'll look into the issue later.

**Comment by asiekierka** [comment]
Fixed in RC3.
