### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by MinecraftLegends** [asiekierka/asielauncher#17]
Resizable window to fit bigger background image.

You need to put a donate button and a link to your wiki/website in it so you get credit and some money out of this.

To be able to display a working link for a website/forum on the launcher itself. 

Since players are most likely to keep this launcher through sever versions of a modpack can the config be synced with the server as well. An example would me be wanted to update the window title with each version of the pack: 1.4 to 1.5

**Comment by asiekierka** [comment]
1. Low on my priority list.
2. I did on MinecraftForum. The money I received is more than enough for now.
3. That is a good idea - will add to 0.4.1 roadmap.
4. That is also planned for 0.4.1.
