### ISSUE TITLE
Delta zip/jar updating

### ISSUE THREAD

**Issue by acertain** [asiekierka/asielauncher#20]
Some kind of zip/jar delta updating. Should detect when zipt/jars move and parts change. Maybe keeps all zips/jars and if server has the old zip/jar the client has, it generates a delta. Maybe do diff/patch on unzipped? Maybe do some kind of bdiff?

Insane far-future feature request.

**Comment by asiekierka** [comment]
Too much work, too much space used for too little gain unless you use mods with a 100MB ZIP like Aether II.
