### ISSUE TITLE
Login error: null

### ISSUE THREAD

**Issue by Gamoholic** [asiekierka/asielauncher#22]
This is a weird one. The first 1.6.2 pack that I put together worked just fine. Now I am trying to put together a different one, but I can't get AsieLauncher to successfully launch. Plus, it appears to be trying to download files that don't exist.

http://servers.asie.pl/server/gamuholic.noip.us:25566

http://pastebin.com/BwC1A9wz

Could it be because I reused settings from the first one? It is no longer running, but I reused its ports and many of its files. I made sure to change things though.

**Comment by Gamoholic** [comment]
This is probably just due to 0.4.1 being early in development. 0.4.0-rc4 works just fine.

**Comment by asiekierka** [comment]
Fixed in 0.4.1 final.
