### ISSUE TITLE
Existing launchers ignore "default": true for new options

### ISSUE THREAD

**Issue by Gamoholic** [asiekierka/asielauncher#25]
I am using the stable channel, 1.5.2. When I add a new option and set "default": true the existing launcher adds the new option, but it is false by default. New launchers work fine. This is not a high priority, just thought I would write it down here so I don't forget.

PS. I was able to use Options to send the lib folder to clients to get around minecraftforge.net derping out.

**Comment by asiekierka** [comment]
This is related to the fact every launcher stores the default-cy of each checkbox on first run - cannot really be fixed without a rewrite of the config system, which at the current rate of development will come in 2038.

**Comment by asiekierka** [comment]
Fixed in 0.4.3-dev.
