### ISSUE TITLE
Must specify the ip address in the also-config.json

### ISSUE THREAD

**Issue by lymem** [asiekierka/asielauncher#37]
By requiring a static ip to be set in the also-config.json, it removes the ability to use aise on hosts where the ip address will change from time to time. It would be easier for many to simple be able to specify the hostname, and have the ip address resolve from that instead. Otherwise people will have to monitor their ip address and manually update the file every time it changes.

**Comment by asiekierka** [comment]
Use DynDNS/no-ip domains and/or edit also-config.json. I might add a "myself" option where it pings to my server and uses that IP.

**Comment by lymem** [comment]
ahh, the field labelled IP in the json file accepts domain names and not just ip addresses.
