### ISSUE TITLE
Server reverts to 0.4.3-dev3 upon automatic update:

### ISSUE THREAD

**Issue by djmixman** [asiekierka/asielauncher#43]
[INFO] Checking for updates...
[INFO] [Updater] Downloading AsieLauncher-latest.jar...
[INFO] [Updater] Downloading AsieLauncher-latest-server.zip...
[INFO] [Updater] Downloaded AsieLauncher-latest-server.zip! Unpacking...
[INFO] [Updater] Downloaded AsieLauncher-latest.jar!
[INFO] Started AsieLauncher server 0.4.3-dev3
[INFO] Gathering server information [server ./]

**Comment by djmixman** [comment]
I was able to work around this using the --skip option when running "node also --skip"

**Comment by asiekierka** [comment]
Should be fixed with 0.4.5.
