### ISSUE TITLE
1.6.4 library downloads use http instead of https

### ISSUE THREAD

**Issue by jakimfett** [asiekierka/asielauncher#44]
I'm getting this error when I attempt to download the modpack for my launcher: http://pastebin.com/ArpHqKNr

The important bit is this: 
INFO: Status: Downloading Minecraft (wait a minute, please)...
java.io.IOException: Server returned HTTP response code: 403 for URL: http://libraries.minecraft.net/net/minecraft/launchwrapper/1.8/launchwrapper-1.8.jar

From what I've been able to determine (see http://www.minecraftforge.net/forum/index.php/topic,14567.0.html for some info), the problem is that the files need to use HTTPS rather than HTTP. For example, "http://libraries.minecraft.net/net/minecraft/launchwrapper/1.8/launchwrapper-1.8.jar" fails to download but "https://libraries.minecraft.net/net/minecraft/launchwrapper/1.8/launchwrapper-1.8.jar" downloads just fine.

**Comment by jakimfett** [comment]
It appears that this is fixed by https://github.com/asiekierka/asielauncher/commit/163857cdd67f5414363c0b1cb4124a5fb43b0b46, however it's now complaining about being unable to download minecraft.jar from http://resources.download.minecraft.net/ (note that it still uses http, not https). Full error report at http://pastebin.com/ssTzv36E

**Comment by ghost** [comment]
I have the same issue . (raise hands)

**Comment by asiekierka** [comment]
Seemingly fixed around 0.4.4.
