### ISSUE TITLE
Reserved file name in Windows: aux.class

### ISSUE THREAD

**Issue by Gamoholic** [asiekierka/asielauncher#5]
Of the 5 people who have tried to use the launcher, 3 of them get stuck at "repacking minecraft.jar". When I have them launch from the command line they all get an error message like this: http://pastebin.com/BfRPAcUL . All three of them are running on Windows 7 and Java 7.

First thing I figured out: you can not create a file named "aux" in Windows. Not even "aux.txt". The main reason I thought to try this was because I remembered someone in #appliedenergistics talking about aux.class in Windows. They were building their own launcher and had to figure out a way around this. I never saw what they came up with.

Second thing: the 3 people who got the error did NOT have vanilla minecraft installed. The 2 of us who didn't have any problems did have vanilla mc. This is the strange one. The launcher downloads the jar from mojang, so why should it matter if you have mc installed already or not? Also, installing vanilla after the fact does not seem to fix the problem.

I'm not sure how hard it would be, but my suggestion would be to unpack the jar into memory, not the hard drive.

**Comment by asiekierka** [comment]
I will be rewriting the ZIP patching system to fix many issues, including this one.

EDIT: Also, the second thing is a mere coincidence. AsieLauncher does not use files from .minecraft AT ALL.

**Comment by asiekierka** [comment]
Fixed in 0.4.0-beta.
