### ISSUE TITLE
Client tries to download from "jarPatches"

### ISSUE THREAD

**Issue by Gamoholic** [asiekierka/asielauncher#8]
![error log 972013](https://f.cloud.github.com/assets/2020623/1102534/2c9855e8-182d-11e3-871a-479494892966.JPG)

"jarPatches" doesn't exist on the server. Should be "jars". Simple mistake ;)

**Comment by asiekierka** [comment]
Actually, jars should be aliased to jarPatches on the server... but I screwed up copypasting ^^;

A fix has been pushed.
