### ISSUE TITLE
Forge not being patched into minecraft.jar (beta4)

### ISSUE THREAD

**Issue by MinecraftLegends** [asiekierka/asielauncher#9]
Client syncs with server and forge.jar is in .asielauncher/servername/jarPatches/ however minecraft is started without forge installed.

**Comment by asiekierka** [comment]
What Minecraft version are you using? In 1.6 and above, you are now supposed to put Forge into ./AsieLauncher/lib. In 1.5.2, that is a very odd occurence in fact. Give more information, if you could.

**Comment by MinecraftLegends** [comment]
1.6.2 it my understanding was it went into jarPatches

**Comment by asiekierka** [comment]
"AsieLauncher/lib" contains libraries. In 1.6 and above, those are used for extra libraries like Forge and LiteLoader.

That's what the documentation says. I will try to clarify it further and/or add a workaround, but I'm closing.

**Comment by Gamoholic** [comment]
Sorry, that was my fault. I haven't made a 1.6.2 pack yet, so I didn't know it was supposed to go in libs.

**Comment by asiekierka** [comment]
It's alright. I will try to clarify it.
